### PR TITLE
added vit sizes (s, b, l, h)

### PR DESCRIPTION
**Pull request by MohammedSB**
#18 
Added ViT Small, Base, Large, and Huge.

(1) I removed the original setup where you can configure the architecture yourself. Now you can **only** chose one of the four sizes. Do you guys want that back? I recommend that we stick with common architectures only.
(2) encoder and decoder are the same sizes. I say keep decoder always base, as is done in the MAE paper.

### CODE REVIEW

**Comment by PaulScotti** [comment]
Yay, thank you Mohammed! 

Before I push can you remove the empty files, __pycache__ files, and test_notebook file you added? (Can update the .gitignore)

**Comment by PaulScotti** [comment]
Also can we remain with using a single models.py file? Not sure why you made it a directory and renamed files around

**Comment by MohammedSB** [comment]
@PaulScotti 

empty init files are used to define python projects, which is important for imports. You can now do an absolute import that is relative to the project dir. 

I made a folder for models to clean things up and make the code more approachable. I don't think we should have everything in one dir, and should probably start organizing the code more. utils for the model should be in models/utils.py for example. Can probably put everything related to downstream in its own folder. etc.

I can organize things up more I guess, if you want me to. Or just leave it as.

**Comment by PaulScotti** [comment]
I very much appreciate organizing things better! but I want to make sure that your changes don't mess up the scripts. For instance, were you able to run main.ipynb without error with these changes? For instance, "my_split_by_node" never gets imported or defined now in the main.ipynb so I would imagine that leads to an error, doesnt it?

**Comment by PaulScotti** [comment]
I pulled your PR and tried to run main.ipynb and there were several errors, making it such that the notebook could not be run. Please check that the scripts are able to run in their default configuration without modifications.

Actually I think let's hold off on organization changes until we discuss more during a working group meeting, could you fix your PR (or close this one and open a new one) such that your changes to the code are simply limited to adding vit size functionality?

**Comment by MohammedSB** [comment]
@PaulScotti sorry, just leave this for now, do not pull it to main.
I am trying to test/fix main.ipynb. I worked locally on this, and the problem is that you can only run main.ipynb on the cluster, since it pulls from S3, so I couldn't test it. So I will set it up on the cluster, first, test it, then give the green light.

I'll try to join the meeting today to discuss this more I guess.

**Pull request closed without merging**
